### PR TITLE
CAW-939: moved functionality from caw_helper to stanford_benefits

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- Moved the code for the additional text format to this module, and out of the `caw_helper` module.

# Review By (Date)
- ASAP

# Criticality
- not critical, but I'd love to get this ticket closed.

Related: https://github.com/SU-SWS/cardinalatwork/pull/5

### CODE REVIEW

**Comment by jbickar** [comment]
w00t

**Comment by jbickar** [comment]
Steps to test?

**Comment by jbickar** [comment]
OIC. Testing steps are in https://github.com/SU-SWS/cardinalatwork/pull/5

**Comment by imonroe** [comment]
Correct.  this work is just duplicated here to keep this repo up to date.

**Review by jbickar — APPROVED** [review]
LGTM

**Pull request merged**
