### PR TITLE
CAW-960: Updates for benefits comparison tool

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- Added a simple composer.json file so we can use composer to manage versions.
- updated the javascript to remove bugfix hacks that had been in place for 2019, and are no longer necessary.
- added a pr template b/c even this repo needs some love.

# Needed By (Date)
- ASAP

# Urgency
- They want to release the benefits comparison pages for 2021 on Monday.

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by jbickar — COMMENTED** [review]
👍 on the composer.json and PR template.

I seem to recall that in the past there was a "2019" and a "2020" button for "shoulder seasons" (such as now). Probably makes sense to check with Mark whether they want that now (for 2020/2021).

**Comment by imonroe** [comment]
yeah, that actually happens through the view, as a part of the `better-exposed-filters` stuff that's being utilized.  There's a fair amount of changes that happen in the UI to support it.  You'll see it works as expected as soon as I've got it up on dev with a fresh copy of the db.

**Comment by jbickar** [comment]
GTK

**Comment by jbickar** [comment]
Am I waiting for this to be pushed up to `dev` to review? I seem to remember this has a tight timeline for next week; feel free to throw something heavy at me tomorrow morning when you get online if so.

**Review by jbickar — APPROVED** [review]
Reviewed on https://cardinalatwork-dev.stanford.edu/benefits-rewards/health/medical-plans/comparison-tool and LGTM; also approved by Mark.

Per Ian, the `CheckYearShowHide()` function "was there to deal with something back in 2019 to do with the EPO/Trio plan, but it was no longer necessary after that point."

**Pull request merged**
